defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.7

version: 2
jobs:
  blackduck_scan:
    <<: *defaults
    resource_class: large
    steps:
      - run:
          name: Installing openjdk
          command: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Pip install requirements
          command: sudo pip install -r requirements.txt
      - run:
          name: Run blackduck
          command: |
            bash <(curl -s -L ${BD_DETECT_URL}) --blackduck.url="${BD_CLIMACELL_APP_URL}" --blackduck.api.token="${BD_API_TOKEN}" --detect.project.name="ldm-config-prod" --detect.project.version.name="production" --detect.pip.requirements.path="requirements.txt"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - blackduck_scan:
          filters:
            branches:
              only: master
          context: climacell-blackduck
